export const HOT_TEAMS = [
  {
    id: 1,
    sport_id: 1,
    country_id: 462,
    venue_id: 214,
    gender: 'male',
    name: 'West Ham United',
    short_code: 'WHU',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/1/1.png',
    founded: 1895,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-17 14:00:00',
  },
  {
    id: 78,
    sport_id: 1,
    country_id: 462,
    venue_id: 480,
    gender: 'male',
    name: 'Brighton & Hove Albion',
    short_code: 'BHA',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/14/78.png',
    founded: 1901,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-14 20:00:00',
  },
  {
    id: 6,
    sport_id: 1,
    country_id: 462,
    venue_id: 281313,
    gender: 'male',
    name: 'Tottenham Hotspur',
    short_code: 'TOT',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/6/6.png',
    founded: 1882,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-16 17:30:00',
  },
  {
    id: 8,
    sport_id: 1,
    country_id: 462,
    venue_id: 230,
    gender: 'male',
    name: 'Liverpool',
    short_code: 'LIV',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/8/8.png',
    founded: 1892,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-17 15:30:00',
  },
  {
    id: 9,
    sport_id: 1,
    country_id: 462,
    venue_id: 151,
    gender: 'male',
    name: 'Manchester City',
    short_code: 'MCI',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/9/9.png',
    founded: 1880,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-16 17:30:00',
  },
  {
    id: 13,
    sport_id: 1,
    country_id: 462,
    venue_id: 12,
    gender: 'male',
    name: 'Everton',
    short_code: 'EVE',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/13/13.png',
    founded: 1878,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-09 12:30:00',
  },
  {
    id: 14,
    sport_id: 1,
    country_id: 462,
    venue_id: 206,
    gender: 'male',
    name: 'Manchester United',
    short_code: 'MUN',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/14/14.png',
    founded: 1878,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-17 15:30:00',
  },
  {
    id: 18,
    sport_id: 1,
    country_id: 462,
    venue_id: 321614,
    gender: 'male',
    name: 'Chelsea',
    short_code: 'CHE',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/18/18.png',
    founded: 1905,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-17 12:45:00',
  },
  {
    id: 19,
    sport_id: 1,
    country_id: 462,
    venue_id: 204,
    gender: 'male',
    name: 'Arsenal',
    short_code: 'ARS',
    image_path: 'https://cdn.sportmonks.com/images/soccer/teams/19/19.png',
    founded: 1886,
    type: 'domestic',
    placeholder: false,
    last_played_at: '2024-03-12 20:00:00',
  },
];

export const HOT_LEAGUES = [
  {
    id: 2,
    sport_id: 1,
    country_id: 41,
    name: 'Champions League',
    active: true,
    short_code: 'UEFA CL',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/2.png',
    type: 'league',
    sub_type: 'cup_international',
    last_played_at: '2024-03-13 20:00:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 5,
    sport_id: 1,
    country_id: 41,
    name: 'Europa League',
    active: true,
    short_code: 'UEFA EL',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/5/5.png',
    type: 'league',
    sub_type: 'cup_international',
    last_played_at: '2024-03-14 20:00:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 8,
    sport_id: 1,
    country_id: 462,
    name: 'Premier League',
    active: true,
    short_code: 'UK PL',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/8/8.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-03-17 14:00:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 24,
    sport_id: 1,
    country_id: 462,
    name: 'FA Cup',
    active: true,
    short_code: 'UK FA Cup',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/24/24.png',
    type: 'league',
    sub_type: 'domestic_cup',
    last_played_at: '2024-03-17 15:30:00',
    category: 2,
    has_jerseys: false,
  },
  {
    id: 82,
    sport_id: 1,
    country_id: 11,
    name: 'Bundesliga',
    active: true,
    short_code: 'GER BI',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/82.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-03-17 16:30:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 301,
    sport_id: 1,
    country_id: 17,
    name: 'Ligue 1',
    active: true,
    short_code: 'FRA L1',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/13/301.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-03-17 19:45:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 384,
    sport_id: 1,
    country_id: 251,
    name: 'Serie A',
    active: true,
    short_code: 'ITA SA',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/0/384.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-03-17 19:45:00',
    category: 1,
    has_jerseys: false,
  },
  {
    id: 564,
    sport_id: 1,
    country_id: 32,
    name: 'La Liga',
    active: true,
    short_code: 'ESP PL',
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/20/564.png',
    type: 'league',
    sub_type: 'domestic',
    last_played_at: '2024-03-17 20:00:00',
    category: 1,
    has_jerseys: false,
  },
  {
    active: true,
    category: 3,
    country_id: 462,
    has_jerseys: false,
    id: 45,
    image_path: 'https://cdn.sportmonks.com/images/soccer/leagues/13/45.png',
    last_played_at: '2024-03-23 12:30:00',
    name: "Women's Super League",
    short_code: null,
    sport_id: 1,
    sub_type: 'domestic',
    type: 'league',
  },
];
