export const EVENT_TYPE = [
  {
    id: 1,
    name: '1st Half',
    code: '1st-half',
    developer_name: '1ST_HALF',
    model_type: 'period',
    stat_group: null,
  },
  {
    id: 2,
    name: '2nd Half',
    code: '2nd-half',
    developer_name: '2ND_HALF',
    model_type: 'period',
    stat_group: null,
  },
  {
    id: 3,
    name: 'Extra Time',
    code: 'extra-time',
    developer_name: 'ET',
    model_type: 'period',
    stat_group: null,
  },
  {
    id: 5,
    name: 'Penalties',
    code: 'penalties',
    developer_name: 'PENALTY_SHOOTOUT',
    model_type: 'period',
    stat_group: null,
  },
  {
    id: 6,
    name: 'Referee',
    code: 'referee',
    developer_name: 'REFEREE',
    model_type: 'referee',
    stat_group: null,
  },
  {
    id: 7,
    name: '1st Assistant',
    code: '1st_assistant',
    developer_name: 'REFEREE_TWO',
    model_type: 'referee',
    stat_group: null,
  },
  {
    id: 8,
    name: '2nd Assistant',
    code: '2nd_assistant',
    developer_name: 'REFEREE_THREE',
    model_type: 'referee',
    stat_group: null,
  },
  {
    id: 9,
    name: '4th Official',
    code: '4th_official',
    developer_name: 'REFEREE_FOUR',
    model_type: 'referee',
    stat_group: null,
  },
  {
    id: 10,
    name: 'VAR',
    code: 'VAR',
    developer_name: 'VAR',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 11,
    name: 'Lineup',
    code: 'lineup',
    developer_name: 'LINEUP',
    model_type: 'lineup',
    stat_group: null,
  },
  {
    id: 12,
    name: 'Bench',
    code: 'bench',
    developer_name: 'BENCH',
    model_type: 'lineup',
    stat_group: null,
  },
  {
    id: 13,
    name: 'Sidelined',
    code: 'sidelined',
    developer_name: 'SIDELINED',
    model_type: 'lineup',
    stat_group: null,
  },
  {
    id: 14,
    name: 'Goal',
    code: 'goal',
    developer_name: 'GOAL',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 15,
    name: 'Own Goal',
    code: 'owngoal',
    developer_name: 'OWNGOAL',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 16,
    name: 'Penalty',
    code: 'penalty',
    developer_name: 'PENALTY',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 17,
    name: 'Missed Penalty',
    code: 'missed_penalty',
    developer_name: 'MISSED_PENALTY',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 18,
    name: 'Substitution',
    code: 'substitution',
    developer_name: 'SUBSTITUTION',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 19,
    name: 'Yellowcard',
    code: 'yellowcard',
    developer_name: 'YELLOWCARD',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 20,
    name: 'Redcard',
    code: 'redcard',
    developer_name: 'REDCARD',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 21,
    name: 'Yellow/Red card',
    code: 'yellowredcard',
    developer_name: 'YELLOWREDCARD',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 22,
    name: 'Penalty Shootout Missed',
    code: 'pen_shootout_miss',
    developer_name: 'PENALTY_SHOOTOUT_MISS',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 23,
    name: 'Penalty Shootout Goal',
    code: 'pen_shootout_goal',
    developer_name: 'PENALTY_SHOOTOUT_GOAL',
    model_type: 'event',
    stat_group: null,
  },
  {
    id: 24,
    name: 'Goalkeeper',
    code: 'goalkeeper',
    developer_name: 'GOALKEEPER',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 25,
    name: 'Defender',
    code: 'defender',
    developer_name: 'DEFENDER',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 26,
    name: 'Midfielder',
    code: 'midfielder',
    developer_name: 'MIDFIELDER',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 27,
    name: 'Attacker',
    code: 'attacker',
    developer_name: 'ATTACKER',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 28,
    name: 'Unknown',
    code: 'unknown',
    developer_name: 'UNKNOWN',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 29,
    name: 'Video',
    code: 'video',
    developer_name: 'VIDEO',
    model_type: 'highlight',
    stat_group: null,
  },
  {
    id: 30,
    name: 'Clip',
    code: 'clip',
    developer_name: 'CLIP',
    model_type: 'highlight',
    stat_group: null,
  },
  {
    id: 31,
    name: 'File',
    code: 'file',
    developer_name: 'FILE',
    model_type: 'highlight',
    stat_group: null,
  },
  {
    id: 32,
    name: 'Probability',
    code: 'probability',
    developer_name: 'PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 33,
    name: 'Valuebet',
    code: 'valuebet',
    developer_name: 'VALUEBET',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 34,
    name: 'Corners',
    code: 'corners',
    developer_name: 'CORNERS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 35,
    name: 'Neutral Venue',
    code: 'neutral_venue',
    developer_name: 'NEUTRAL_VENUE',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 36,
    name: 'Kickoff',
    code: 'kickoff',
    developer_name: 'KICKOFF',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 37,
    name: 'Match Details',
    code: 'match_details',
    developer_name: 'MATCH_DETAILS',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 39,
    name: 'Extra Time - 2nd Half',
    code: 'extra-time-2nd-half',
    developer_name: 'ET_2ND_HALF',
    model_type: 'period',
    stat_group: null,
  },
  {
    id: 40,
    name: 'Captain',
    code: 'captain',
    developer_name: 'CAPTAIN',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 41,
    name: 'Shots Off Target',
    code: 'shots-off-target',
    developer_name: 'SHOTS_OFF_TARGET',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 42,
    name: 'Shots Total',
    code: 'shots-total',
    developer_name: 'SHOTS_TOTAL',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 43,
    name: 'Attacks',
    code: 'attacks',
    developer_name: 'ATTACKS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 44,
    name: 'Dangerous Attacks',
    code: 'dangerous-attacks',
    developer_name: 'DANGEROUS_ATTACKS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 45,
    name: 'Ball Possession %',
    code: 'ball-possession',
    developer_name: 'BALL_POSSESSION',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 46,
    name: 'Ball Safe',
    code: 'ball-safe',
    developer_name: 'BALL_SAFE',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 47,
    name: 'Penalties',
    code: 'penalties',
    developer_name: 'PENALTIES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 49,
    name: 'Shots Insidebox',
    code: 'shots-insidebox',
    developer_name: 'SHOTS_INSIDEBOX',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 50,
    name: 'Shots Outsidebox',
    code: 'shots-outsidebox',
    developer_name: 'SHOTS_OUTSIDEBOX',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 51,
    name: 'Offsides',
    code: 'offsides',
    developer_name: 'OFFSIDES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 52,
    name: 'Goals',
    code: 'goals',
    developer_name: 'GOALS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 53,
    name: 'Goal Kicks',
    code: 'goals-kicks',
    developer_name: 'GOAL_KICKS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 54,
    name: 'Goal Attempts',
    code: 'goal-attempts',
    developer_name: 'GOAL_ATTEMPTS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 55,
    name: 'Free Kicks',
    code: 'free-kicks',
    developer_name: 'FREE_KICKS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 56,
    name: 'Fouls',
    code: 'fouls',
    developer_name: 'FOULS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 57,
    name: 'Saves',
    code: 'saves',
    developer_name: 'SAVES',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 58,
    name: 'Shots Blocked',
    code: 'shots-blocked',
    developer_name: 'SHOTS_BLOCKED',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 59,
    name: 'Substitutions',
    code: 'substitutions',
    developer_name: 'SUBSTITUTIONS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 60,
    name: 'Throwins',
    code: 'throwins',
    developer_name: 'THROWINS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 61,
    name: 'Beats',
    code: 'beats',
    developer_name: 'BEATS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 62,
    name: 'Long Passes',
    code: 'long-passes',
    developer_name: 'LONG_PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 63,
    name: 'Short Passes',
    code: 'short-passes',
    developer_name: 'SHORT_PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 64,
    name: 'Hit Woodwork',
    code: 'hit-woodwork',
    developer_name: 'HIT_WOODWORK',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 65,
    name: 'Successful Headers',
    code: 'successful-headers',
    developer_name: 'SUCCESSFUL_HEADERS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 66,
    name: 'Successful Interceptions',
    code: 'successful-interceptions',
    developer_name: 'SUCCESSFUL_INTERCEPTIONS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 67,
    name: 'Successful Centers',
    code: 'successful-centers',
    developer_name: 'SUCCESSFUL_CENTERS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 68,
    name: 'Substitutions Overtime',
    code: 'substitutions-overtime',
    developer_name: 'SUBSTITUTIONS_OVERTIME',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 69,
    name: 'Offsides Overtime',
    code: 'offsides-overtime',
    developer_name: 'OFFSIDES_OVERTIME',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 70,
    name: 'Headers',
    code: 'headers',
    developer_name: 'HEADERS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 71,
    name: 'Last Substituttion',
    code: 'last-substituttion',
    developer_name: 'LAST_SUBSTITUTION',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 72,
    name: 'First Substitution',
    code: 'first-substitution',
    developer_name: 'FIRST_SUBSTITUTION',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 73,
    name: 'Successful Center',
    code: 'successful-center',
    developer_name: 'SUCCESSFUL_CENTER',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 74,
    name: 'Yellowcards Overtime',
    code: 'yellowcards-overtime',
    developer_name: 'YELLOWCARDS_OVERTIME',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 75,
    name: 'Corners Overtime',
    code: 'corners-overtime',
    developer_name: 'CORNERS_OVERTIME',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 76,
    name: 'Goalkeeper Comes Out',
    code: 'goalkeeper-comes-out',
    developer_name: 'GOALKEEPER_COME_OUTS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 77,
    name: 'Challenges',
    code: 'challenges',
    developer_name: 'CHALLENGES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 78,
    name: 'Tackles',
    code: 'tackles',
    developer_name: 'TACKLES',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 79,
    name: 'Assists',
    code: 'assists',
    developer_name: 'ASSISTS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 80,
    name: 'Passes',
    code: 'passes',
    developer_name: 'PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 81,
    name: 'Successful Passes',
    code: 'successful-passes',
    developer_name: 'SUCCESSFUL_PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 82,
    name: 'Successful Passes Percentage',
    code: 'successful-passes-percentage',
    developer_name: 'SUCCESSFUL_PASSES_PERCENTAGE',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 83,
    name: 'Redcards',
    code: 'redcards',
    developer_name: 'REDCARDS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 84,
    name: 'Yellowcards',
    code: 'yellowcards',
    developer_name: 'YELLOWCARDS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 85,
    name: 'Yellowred Cards',
    code: 'yellowred-cards',
    developer_name: 'YELLOWRED_CARDS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 86,
    name: 'Shots On Target',
    code: 'shots-on-target',
    developer_name: 'SHOTS_ON_TARGET',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 87,
    name: 'Injuries',
    code: 'injuries',
    developer_name: 'INJURIES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 88,
    name: 'Goals Conceded',
    code: 'goals-conceded',
    developer_name: 'GOALS_CONCEDED',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 91,
    name: 'First Offside',
    code: 'first-offside',
    developer_name: 'FIRST_OFFSIDE',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 92,
    name: 'Last Offside',
    code: 'last-offside',
    developer_name: 'LAST_OFFSIDE',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 94,
    name: 'Dispossessed',
    code: 'dispossessed',
    developer_name: 'DISPOSSESSED',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 95,
    name: 'Offsides Provoked',
    code: 'offsides-provoked',
    developer_name: 'OFFSIDES_PROVOKED',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 96,
    name: 'Fouls Drawn',
    code: 'fouls-drawn',
    developer_name: 'FOULS_DRAWN',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 97,
    name: 'Blocked Shots',
    code: 'blocked-shots',
    developer_name: 'BLOCKED_SHOTS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 98,
    name: 'Total Crosses',
    code: 'total-crosses',
    developer_name: 'TOTAL_CROSSES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 99,
    name: 'Accurate Crosses',
    code: 'accurate-crosses',
    developer_name: 'ACCURATE_CROSSES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 100,
    name: 'Interceptions',
    code: 'interceptions',
    developer_name: 'INTERCEPTIONS',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 101,
    name: 'Clearances',
    code: 'clearances',
    developer_name: 'CLEARANCES',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 102,
    name: 'Clearances Won',
    code: 'clearances-won',
    developer_name: 'CLEARANCES_WON',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 103,
    name: 'Punches',
    code: 'punches',
    developer_name: 'PUNCHES',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 104,
    name: 'Saves Insidebox',
    code: 'saves-insidebox',
    developer_name: 'SAVES_INSIDE_BOX',
    model_type: 'statistic',
    stat_group: 'defensive',
  },
  {
    id: 105,
    name: 'Total Duels',
    code: 'total-duels',
    developer_name: 'TOTAL_DUELS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 106,
    name: 'Duels Won',
    code: 'duels-won',
    developer_name: 'DUELS_WON',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 107,
    name: 'Aerials Won',
    code: 'aeriels-won',
    developer_name: 'AERIALS_WON',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 108,
    name: 'Dribble Attempts',
    code: 'dribble-attempts',
    developer_name: 'DRIBBLED_ATTEMPTS',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 109,
    name: 'Successful Dribbles',
    code: 'successful-dribbles',
    developer_name: 'SUCCESSFUL_DRIBBLES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 110,
    name: 'Dribbled Past',
    code: 'dribbled-past',
    developer_name: 'DRIBBLED_PAST',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 111,
    name: 'Penalties Scored',
    code: 'penalties-scored',
    developer_name: 'PENALTIES_SCORED',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 112,
    name: 'Penalties Missed',
    code: 'penalties-missed',
    developer_name: 'PENALTIES_MISSES',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 113,
    name: 'Penalties Saved',
    code: 'penalties-saved',
    developer_name: 'PENALTIES_SAVED',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 114,
    name: 'Penalties Committed',
    code: 'penalties-committed',
    developer_name: 'PENALTIES_COMMITTED',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 115,
    name: 'Penalties Won',
    code: 'penalties-won',
    developer_name: 'PENALTIES_WON',
    model_type: 'statistic',
    stat_group: 'offensive',
  },
  {
    id: 116,
    name: 'Accurate Passes',
    code: 'accurate-passes',
    developer_name: 'ACCURATE_PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 117,
    name: 'Key Passes',
    code: 'key-passes',
    developer_name: 'KEY_PASSES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 118,
    name: 'Rating',
    code: 'rating',
    developer_name: 'RATING',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 119,
    name: 'Minutes Played',
    code: 'minutes-played',
    developer_name: 'MINUTES_PLAYED',
    model_type: 'statistic',
    stat_group: 'NULL',
  },
  {
    id: 120,
    name: 'Touches',
    code: 'touches',
    developer_name: 'TOUCHES',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 121,
    name: 'Turn Over',
    code: 'turn-over',
    developer_name: 'TURN_OVER',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 122,
    name: 'Long Balls',
    code: 'long-balls',
    developer_name: 'LONG_BALLS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 123,
    name: 'Long Balls Won',
    code: 'long-balls-won',
    developer_name: 'LONG_BALLS_WON',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 124,
    name: 'Through Balls',
    code: 'through-balls',
    developer_name: 'THROUGH_BALLS',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 125,
    name: 'Through Balls Won',
    code: 'through-balls-won',
    developer_name: 'THROUGH_BALLS_WON',
    model_type: 'statistic',
    stat_group: 'overall',
  },
  {
    id: 126,
    name: 'Corner',
    code: 'corner',
    developer_name: 'CORNER',
    model_type: 'timeline',
    stat_group: 'offensive',
  },
  {
    id: 129,
    name: 'Overall Matched Played',
    code: 'overall-matches-played',
    developer_name: 'OVERALL_MATCHES',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 130,
    name: 'Overall Won',
    code: 'overall-won',
    developer_name: 'OVERALL_WINS',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 131,
    name: 'Overall Draw',
    code: 'overall-draw',
    developer_name: 'OVERALL_DRAWS',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 132,
    name: 'Overall Lost',
    code: 'overall-lost',
    developer_name: 'OVERALL_LOST',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 133,
    name: 'Overal Goals Scored',
    code: 'overall-goals-for',
    developer_name: 'OVERALL_SCORED',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 134,
    name: 'Overall Goals Conceded',
    code: 'overall-goals-against',
    developer_name: 'OVERALL_CONCEDED',
    model_type: 'standings',
    stat_group: 'overall',
  },
  {
    id: 135,
    name: 'Home Matched Played',
    code: 'home-matches-played',
    developer_name: 'HOME_MATCHES',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 136,
    name: 'Home Won',
    code: 'home-won',
    developer_name: 'HOME_WINS',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 137,
    name: 'Home Draw',
    code: 'home-draw',
    developer_name: 'HOME_DRAWS',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 138,
    name: 'Home Lost',
    code: 'home-lost',
    developer_name: 'HOME_LOST',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 139,
    name: 'Home Goals Scored',
    code: 'home-scored',
    developer_name: 'HOME_SCORED',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 140,
    name: 'Home Goals Conceded',
    code: 'home-conceded',
    developer_name: 'HOME_CONCEDED',
    model_type: 'standings',
    stat_group: 'home',
  },
  {
    id: 141,
    name: 'Away Matched Played',
    code: 'away-matches-played',
    developer_name: 'AWAY_MATCHES',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 142,
    name: 'Away Won',
    code: 'away-won',
    developer_name: 'AWAY_WINS',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 143,
    name: 'Away Draw',
    code: 'away-draw',
    developer_name: 'AWAY_DRAWS',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 144,
    name: 'Away Lost',
    code: 'away-lost',
    developer_name: 'AWAY_LOST',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 145,
    name: 'Away Goals Scored',
    code: 'away-scored',
    developer_name: 'AWAY_SCORED',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 146,
    name: 'Away Goals Conceded',
    code: 'away-conceded',
    developer_name: 'AWAY_CONCEDED',
    model_type: 'standings',
    stat_group: 'away',
  },
  {
    id: 147,
    name: 'Promotion',
    code: 'promotion',
    developer_name: 'PROMOTION',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 148,
    name: 'Centre Back',
    code: 'centre-back',
    developer_name: 'CENTRE_BACK',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 149,
    name: 'Defensive Midfield',
    code: 'defensive-midfied',
    developer_name: 'DEFENSIVE_MIDFIELD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 150,
    name: 'Attacking Midfield',
    code: 'attacking-midfied',
    developer_name: 'ATTACKING_MIDFIELD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 151,
    name: 'Centre Forward',
    code: 'centre-forward',
    developer_name: 'CENTRE_FORWARD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 152,
    name: 'Left Wing',
    code: 'left-wing',
    developer_name: 'LEFT_WING',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 153,
    name: 'Central Midfield',
    code: 'central-midfied',
    developer_name: 'CENTRAL_MIDFIELD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 154,
    name: 'Right Back',
    code: 'right-back',
    developer_name: 'RIGHT_BACK',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 155,
    name: 'Left Back',
    code: 'left-back',
    developer_name: 'LEFT_BACK',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 156,
    name: 'Right Wing',
    code: 'right-wing',
    developer_name: 'RIGHT_WING',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 157,
    name: 'Left Midfield',
    code: 'left-midfield',
    developer_name: 'LEFT_MIDFIELD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 158,
    name: 'Right Midfield',
    code: 'right-midfield',
    developer_name: 'RIGHT_MIDFIELD',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 159,
    name: 'Formation',
    code: 'formation',
    developer_name: 'FORMATION',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 160,
    name: 'Ball Coordinates',
    code: 'ball-coordinates',
    developer_name: 'BALL_COORDINATES',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 161,
    name: 'Home Participant Colors',
    code: 'home-participany-colors',
    developer_name: 'HOME_PARTICIPANT_COLORS',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 162,
    name: 'Away Participant Colors',
    code: 'away-participany-colors',
    developer_name: 'AWAY_PARTICIPANT_COLORS',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 163,
    name: 'Secondary Striker',
    code: 'secondary_striker',
    developer_name: 'SECONDARY_STRIKER',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 164,
    name: 'Has Standings',
    code: 'has-standings',
    developer_name: 'HAS_STANDING',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 165,
    name: 'Has Topscorers',
    code: 'has-topscorers',
    developer_name: 'HAS_TOPSCORERS',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 168,
    name: '8th Finals',
    code: '8th-finals',
    developer_name: '8TH_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 169,
    name: 'Points',
    code: 'points',
    developer_name: 'POINTS',
    model_type: 'tie_breaker_rule',
    stat_group: null,
  },
  {
    id: 170,
    name: 'Head to Head',
    code: 'head-to-head',
    developer_name: 'HEAD_TO_HEAD',
    model_type: 'tie_breaker_rule',
    stat_group: null,
  },
  {
    id: 171,
    name: 'Goal Difference, Matches Played, Goals Scored',
    code: 'goal-difference',
    developer_name: 'GOAL_DIFFERENCE',
    model_type: 'tie_breaker_rule',
    stat_group: null,
  },
  {
    id: 172,
    name: 'Split Points Rule',
    code: 'split-points-rule',
    developer_name: 'SPLIT_POINTS_RULE',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 173,
    name: 'Points',
    code: 'points',
    developer_name: 'POINTS',
    model_type: 'standing_correction',
    stat_group: null,
  },
  {
    id: 174,
    name: 'Goals For',
    code: 'goals-for',
    developer_name: 'GOALS_FOR',
    model_type: 'standing_correction',
    stat_group: null,
  },
  {
    id: 175,
    name: 'Goals Against',
    code: 'goals-aginst',
    developer_name: 'GOALS_AGAINST',
    model_type: 'standing_correction',
    stat_group: null,
  },
  {
    id: 176,
    name: 'Streak',
    code: 'streak',
    developer_name: 'STREAK',
    model_type: 'standings',
    stat_group: null,
  },
  {
    id: 179,
    name: 'Goal Difference',
    code: 'goal-difference',
    developer_name: 'OVERALL_GOAL_DIFFERENCE',
    model_type: 'standings',
    stat_group: null,
  },
  {
    id: 180,
    name: 'UEFA Champions League',
    code: 'uefa-champions-league',
    developer_name: 'UEFA_CHAMPIONS_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 181,
    name: 'UEFA Europa League',
    code: 'uefa-europa-league',
    developer_name: 'UEFA_EUROPA_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 182,
    name: 'Relegation',
    code: 'relegation',
    developer_name: 'RELEGATION',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 183,
    name: 'Championship Round',
    code: 'championship-round',
    developer_name: 'CHAMPIONSHIP_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 184,
    name: 'Relegation Round',
    code: 'relegation-round',
    developer_name: 'RELEGATION_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 185,
    name: 'Home Points',
    code: 'home-points',
    developer_name: 'HOME_POINTS',
    model_type: 'standings',
    stat_group: null,
  },
  {
    id: 186,
    name: 'Away Points',
    code: 'away-points',
    developer_name: 'AWAY_POINTS',
    model_type: 'standings',
    stat_group: null,
  },
  {
    id: 187,
    name: 'Overall Points',
    code: 'overall-points',
    developer_name: 'TOTAL_POINTS',
    model_type: 'standings',
    stat_group: null,
  },
  {
    id: 188,
    name: 'Season Matches',
    code: 'matches',
    developer_name: 'MATCHES',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 189,
    name: 'Season Teams',
    code: 'total-teams',
    developer_name: 'TOTAL_TEAMS',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 190,
    name: 'Matches Ended In Draw',
    code: 'matches-ended-in-draw',
    developer_name: 'MATCHES_ENDED_IN_DRAW',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 191,
    name: 'Number Of Goals',
    code: 'number-of-goals',
    developer_name: 'NUMBER_OF_GOALS',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 192,
    name: 'Both Teams To Score',
    code: 'btts',
    developer_name: 'BTTS',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 193,
    name: 'Cards',
    code: 'cards',
    developer_name: 'CARDS',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 194,
    name: 'Cleansheets',
    code: 'cleansheets',
    developer_name: 'CLEANSHEET',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 195,
    name: 'Goalkeeper Cleansheets',
    code: 'goalkeeper-cleansheets',
    developer_name: 'GOALKEEPER_CLEANSHEET',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 196,
    name: 'Scoring Minutes',
    code: 'scoring-minutes',
    developer_name: 'SCORING_MINUTES',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 197,
    name: 'Goal Line',
    code: 'goal-line',
    developer_name: 'GOAL_LINE',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 201,
    name: 'Win Percentage',
    code: 'win-percentage',
    developer_name: 'WIN_PERCENTAGE',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 202,
    name: 'Defeat Percentage',
    code: 'defeat-percentage',
    developer_name: 'DEFEAT_PERCENTAGE',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 203,
    name: 'Draw Percentage',
    code: 'draw-percentage',
    developer_name: 'DRAW_PERCENTAGE',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 204,
    name: 'Most Scored',
    code: 'participant-most-scored',
    developer_name: 'PARTICIPANT_MOST_SCORED',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 205,
    name: 'Most Conceded',
    code: 'participant-most-conceded',
    developer_name: 'PARTICIPANT_MOST_CONCEDED',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 206,
    name: 'Most Scored Per Match',
    code: 'participant-most-scored-per-match',
    developer_name: 'PARTICIPANT_MOST_SCORED_PER_MATCH',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 207,
    name: 'Most Conceded Per Match',
    code: 'participant-most-conceded-per-match',
    developer_name: 'PARTICIPANT_MOST_CONCEDED_PER_MATCH',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 208,
    name: 'Goal Topscorer',
    code: 'goal-topscorer',
    developer_name: 'GOAL_TOPSCORER',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 209,
    name: 'Assist Topscorer',
    code: 'assist-topscorer',
    developer_name: 'ASSIST_TOPSCORER',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 210,
    name: 'Card Topscorer',
    code: 'card-topscorer',
    developer_name: 'CARD_TOPSCORER',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 211,
    name: 'Highest Rated Player',
    code: 'highest-rated-player',
    developer_name: 'HIGHEST_RATED_PLAYER',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 212,
    name: 'Highest Rated Team',
    code: 'highest-rated-team',
    developer_name: 'HIGHEST_RATED_TEAM',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 213,
    name: 'Conceded Scoring Minutes',
    code: 'conceded-scoring-minutes',
    developer_name: 'CONCEDED_SCORING_MINUTES',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 214,
    name: 'Team Wins',
    code: 'team-wins',
    developer_name: 'WIN',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 215,
    name: 'Team Draws',
    code: 'team-draws',
    developer_name: 'DRAW',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 216,
    name: 'Team Lost',
    code: 'team-lost',
    developer_name: 'LOST',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 217,
    name: 'Major League',
    code: 'major-league',
    developer_name: 'MAJOR_LEAGUE',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 218,
    name: 'Loan',
    code: 'loan-transfer',
    developer_name: 'LOAN_TRANSFER',
    model_type: 'transfer',
    stat_group: null,
  },
  {
    id: 219,
    name: 'Transfer',
    code: 'transfer',
    developer_name: 'TRANSFER',
    model_type: 'transfer',
    stat_group: null,
  },
  {
    id: 220,
    name: 'Free Transfer',
    code: 'free-transfer',
    developer_name: 'FREE_TRANSFER',
    model_type: 'transfer',
    stat_group: null,
  },
  {
    id: 221,
    name: 'Coach',
    code: 'coach',
    developer_name: 'COACH',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 222,
    name: 'Provides News',
    code: 'provides-news',
    developer_name: 'PROVIDES_NEWS',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 223,
    name: 'Group Stage',
    code: 'group-stage',
    developer_name: 'GROUP_STAGE',
    model_type: 'stage_type',
    stat_group: null,
  },
  {
    id: 224,
    name: 'Knock Out',
    code: 'knock-out',
    developer_name: 'KNOCK_OUT',
    model_type: 'stage_type',
    stat_group: null,
  },
  {
    id: 225,
    name: 'Qualifying',
    code: 'qualifying',
    developer_name: 'QUALIFYING',
    model_type: 'stage_type',
    stat_group: null,
  },
  {
    id: 226,
    name: 'Assistant Coach',
    code: 'assistant-coach',
    developer_name: 'ASSISTANT_COACH',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 227,
    name: 'Goalkeeping Coach',
    code: 'goalkeeping-coach',
    developer_name: 'GOALKEEPING_COACH',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 228,
    name: 'Forward Coach',
    code: 'forward-coach',
    developer_name: 'FORWARD_COACH',
    model_type: 'position',
    stat_group: null,
  },
  {
    id: 229,
    name: 'Preferred Foot',
    code: 'preferred-foot',
    developer_name: 'PREFERRED_FOOT',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 230,
    name: 'Rule Color',
    code: 'rule-color',
    developer_name: 'RULE_COLOR',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 231,
    name: 'Both Teams To Score Probability',
    code: 'both-teams-to-score-probability',
    developer_name: 'BTTS_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 232,
    name: 'Half Time/Full Time Probability',
    code: 'half-time-full-time-probability',
    developer_name: 'HTFT_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 233,
    name: 'First Half Winner Probability',
    code: 'first-half-winner',
    developer_name: 'FIRST_HALF_WINNER_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 234,
    name: 'Over/Under 1.5 Probability',
    code: 'over-under-1_5-probability',
    developer_name: 'OVER_UNDER_1_5_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 235,
    name: 'Over/Under 2.5 Probability',
    code: 'over-under-2_5-probability',
    developer_name: 'OVER_UNDER_2_5_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 236,
    name: 'Over/Under 3.5 Probability',
    code: 'over-under-3_5_probability',
    developer_name: 'OVER_UNDER_3_5_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 237,
    name: 'Fulltime Result Probability',
    code: 'fulltime-result-probability',
    developer_name: 'FULLTIME_RESULT_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 238,
    name: 'Team To Score First Probability',
    code: 'team_to_score_first-probability',
    developer_name: 'TEAM_TO_SCORE_FIRST_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 239,
    name: 'Double Chance Probability',
    code: 'double_chance-probability',
    developer_name: 'DOUBLE_CHANCE_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 240,
    name: 'Correct Score Probability',
    code: 'correct-score-probability',
    developer_name: 'CORRECT_SCORE_PROBABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 241,
    name: 'Historical Log Loss',
    code: 'historical-log-loss',
    developer_name: 'HISTORICAL_LOG_LOSS',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 242,
    name: 'Model Hit Ratio',
    code: 'model-hit-ratio',
    developer_name: 'MODEL_HIT_RATIO',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 243,
    name: 'Model Predictability',
    code: 'model-predictability',
    developer_name: 'MODEL_PREDICTABILITY',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 244,
    name: 'Model Predictive Power',
    code: 'model-predictive-power',
    developer_name: 'MODEL_PREDICTIVE_POWER',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 245,
    name: 'Models Log Loss',
    code: 'models-log-loss',
    developer_name: 'MODELS_LOG_LOSS',
    model_type: 'prediction',
    stat_group: null,
  },
  {
    id: 246,
    name: 'UEFA Champions League Qualifiers',
    code: 'uefa-champions-league-qualifiers',
    developer_name: 'UEFA_CHAMPIONS_LEAGUE_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 247,
    name: 'UEFA Cup',
    code: 'uefa-cup',
    developer_name: 'UEFA_CUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 248,
    name: 'Intertoto Cup',
    code: 'intertoto-cup',
    developer_name: 'INTERTOTO_CUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 249,
    name: 'Relegation Play-off',
    code: 'relegation-play-off',
    developer_name: 'RELEGATION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 250,
    name: 'Possible Relegation',
    code: 'possible-relegation',
    developer_name: 'POSSIBLE__RELEGATION',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 251,
    name: 'Promotion Group',
    code: 'promotion-group',
    developer_name: 'PROMOTION_GROUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 252,
    name: 'Relegation Group',
    code: 'relegation-group',
    developer_name: 'RELEGATION_GROUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 254,
    name: 'Champions League Qualifiers Play-off',
    code: 'champions-league-qualifiers-play-off',
    developer_name: 'CHAMPIONS_LEAGUE_QUALIFIERS_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 255,
    name: 'Next Round',
    code: 'next-round',
    developer_name: 'NEXT_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 256,
    name: 'Semi-finals',
    code: 'semi-finals',
    developer_name: 'SEMI_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 257,
    name: 'Final Tournament',
    code: 'final-tournament',
    developer_name: 'FINAL_TOURNAMENT',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 258,
    name: 'Intercontinental Play-off',
    code: 'intercontinental-play-off',
    developer_name: 'INTERCONTINENTAL_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 259,
    name: 'Final Tournament or Play-offs',
    code: 'final-tournament-or-play-offs',
    developer_name: 'FINAL_TOURNAMENT_OR_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 260,
    name: 'AFC Champions League Qualifiers',
    code: 'afc-champions-league-qualifiers',
    developer_name: 'AFC_CHAMPIONS_LEAGUE_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 261,
    name: 'AFC Cup',
    code: 'afc-cup',
    developer_name: 'AFC_CUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 262,
    name: 'Possible 8th Finals',
    code: 'possible-8th-finals',
    developer_name: 'POSSIBLE_8TH_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 263,
    name: 'UEFA Europa League Play-off',
    code: 'uefa-europa-league-play-off',
    developer_name: 'UEFA_EUROPA_LEAGUE_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 264,
    name: 'Promotion Play-off',
    code: 'promotion-play-off',
    developer_name: 'PROMOTION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 265,
    name: 'UEFA Europa League Qualifiers',
    code: 'uefa-europa-league-qualifiers',
    developer_name: 'UEFA_EUROPA_LEAGUE_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 266,
    name: 'Middle Play-off',
    code: 'middle-play-off',
    developer_name: 'MIDDLE_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 267,
    name: 'Champion',
    code: 'champion',
    developer_name: 'CHAMPION',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 268,
    name: 'CONMEBOL Libertadores',
    code: 'conmebol-libertadores',
    developer_name: 'CONMEBOL_LIBERTADORES',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 269,
    name: 'Final Series Play-offs',
    code: 'final-series-play-offs',
    developer_name: 'FINAL_SERIES_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 270,
    name: 'Possible Final',
    code: 'possible-final',
    developer_name: 'POSSIBLE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 271,
    name: 'Possible Final Tournament',
    code: 'possible-final-tournament',
    developer_name: 'POSSIBLE_FINAL_TOURNAMENT',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 272,
    name: 'Possible Next Round',
    code: 'possible-next-round',
    developer_name: 'POSSIBLE_NEXT_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 273,
    name: 'CAF Champions League',
    code: 'caf-champions-league',
    developer_name: 'CAF_CHAMPIONS_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 274,
    name: 'CAF Confederation Cup',
    code: 'caf-confederation-cup',
    developer_name: 'CAF_CONFEDERATION_CUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 275,
    name: 'Quarter-finals',
    code: 'quarter-finals',
    developer_name: 'QUARTER_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 276,
    name: 'Possible Semi-finals',
    code: 'possible-semi-finals',
    developer_name: 'POSSIBLE_SEMI_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 277,
    name: 'World Cup',
    code: 'world-cup',
    developer_name: 'WORLD_CUP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 278,
    name: 'Play-off',
    code: 'play-off',
    developer_name: 'PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 279,
    name: 'Final Series',
    code: 'final-series',
    developer_name: 'FINAL_SERIES',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 280,
    name: 'Final',
    code: 'final',
    developer_name: 'FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 281,
    name: 'CONCACAF Champions League',
    code: 'concacaf-champions-league',
    developer_name: 'CONCACAF_CHAMPIONS_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 282,
    name: 'Lower Table Round',
    code: 'lower-table-round',
    developer_name: 'LOWER_TABLE_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 283,
    name: 'CAF Champions League Qualifiers',
    code: 'caf-champions-league-qualifiers',
    developer_name: 'CAF_CHAMPIONS_LEAGUE_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 284,
    name: 'AFC Champions League',
    code: 'afc-champions-league',
    developer_name: 'AFC_CHAMPIONS_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 285,
    name: 'CFU Club Championship',
    code: 'cfu-club-championship',
    developer_name: 'CFU_CLUB_CHAMPIONSHIP',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 286,
    name: 'CONMEBOL Libertadores Qualifiers',
    code: 'conmebol-libertadores-qualifiers',
    developer_name: 'CONMEBOL_LIBERTADORES_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 287,
    name: 'CONMEBOL Sudamericana',
    code: 'conmebol-sudamericana',
    developer_name: 'CONMEBOL_SUDAMERICANA',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 288,
    name: 'Champion Play-off',
    code: 'champion-play-off',
    developer_name: 'CHAMPION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 289,
    name: 'UEFA Conference League Qualifiers',
    code: 'uefa-conference-league-qualifiers',
    developer_name: 'UEFA_CONFERENCE_LEAGUE_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 290,
    name: 'AFC Cup Play-offs',
    code: 'afc-cup-play-offs',
    developer_name: 'AFC_CUP_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 291,
    name: 'Championship Round Play-offs',
    code: 'championship-round-play-offs',
    developer_name: 'CHAMPIONSHIP_ROUND_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 292,
    name: 'Possible Promotion Play-off',
    code: 'possible-promotion-play-off',
    developer_name: 'POSSIBLE_PROMOTION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 293,
    name: 'UEFA Conference League Play-offs',
    code: 'uefa-conference-league-play-offs',
    developer_name: 'UEFA_CONFERENCE_LEAGUE_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 294,
    name: '3rd Place Final',
    code: '3rd-place-final',
    developer_name: '3RD_PLACE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 295,
    name: 'Bottom Play-offs',
    code: 'bottom-play-offs',
    developer_name: 'BOTTOM_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 296,
    name: 'OFC Champions League',
    code: 'ofc-champions-league',
    developer_name: 'OFC_CHAMPIONS_LEAGUE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 297,
    name: 'Possible Quarter-finals',
    code: 'possible-quarter-finals',
    developer_name: 'POSSIBLE_QUARTER_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 298,
    name: '16th Finals',
    code: '16th-finals',
    developer_name: '16TH_FINALS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 299,
    name: 'UEFA Conference League Qualifiers Play-off',
    code: 'uefa-conference-league-qualifiers-play-off',
    developer_name: 'UEFA_CONFERENCE_LEAGUE_QUALIFIERS_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 300,
    name: 'Preliminary Promotion Play-off',
    code: 'preliminary-promotion-play-off',
    developer_name: 'PRELIMINARY_PROMOTION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 301,
    name: 'Final Round Play-off',
    code: 'final-round-play-off',
    developer_name: 'FINAL_ROUND_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 302,
    name: 'CAF Confederation Cup Qualifiers',
    code: 'caf-confederation-cup-qualifiers',
    developer_name: 'CAF_CONFEDERATION_CUP_QUALIFIERS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 303,
    name: '5th-8th Place Play-offs',
    code: '5th-8th-place-play-offs',
    developer_name: '5TH_8TH_PLACE_PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 304,
    name: '5th Place Final',
    code: '5th-place-final',
    developer_name: '5TH_PLACE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 305,
    name: '7th Place Final',
    code: '7th-place-final',
    developer_name: '7TH_PLACE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 306,
    name: 'Final Serie',
    code: 'final-serie',
    developer_name: 'FINAL_SERIE',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 307,
    name: 'Play-offs',
    code: 'play-offs',
    developer_name: 'PLAY_OFFS',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 308,
    name: '9th Place Final',
    code: '9th-place-final',
    developer_name: '9TH_PLACE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 309,
    name: '11th Place Final',
    code: '11th-place-final',
    developer_name: '11TH_PLACE_FINAL',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 310,
    name: 'Possible Final Series',
    code: 'possible-final-series',
    developer_name: 'POSSIBLE_FINAL_SERIES',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 311,
    name: 'Possible Play-off',
    code: 'possible-play-off',
    developer_name: 'POSSIBLE_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 312,
    name: 'Possible Relegation Play-off',
    code: 'possible-relegation-play-off',
    developer_name: 'POSSIBLE_RELEGATION_PLAY_OFF',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 313,
    name: 'Possible Promotion',
    code: 'possible-promotion',
    developer_name: 'POSSIBLE_PROMOTION',
    model_type: 'standing_rule',
    stat_group: null,
  },
  {
    id: 314,
    name: 'VAR Moments',
    code: 'var-moments',
    developer_name: 'VAR_MOMENTS',
    model_type: 'statistic',
    stat_group: null,
  },
  {
    id: 315,
    name: 'Has Outgroup Matches',
    code: 'outgroup-matches',
    developer_name: 'OUTGROUP_MATCHES',
    model_type: 'metadata',
    stat_group: null,
  },
  {
    id: 316,
    name: 'Championship Round Relegation Round',
    code: 'championship-round-relegation-round',
    developer_name: 'CHAMPIONSHIP_ROUND_RELEGATION_ROUND',
    model_type: 'standing_rule',
    stat_group: null,
  },
];

export const STATE = [
  {
    id: 1,
    state: 'NS',
    name: 'Not Started',
    short_name: 'NS',
    developer_name: 'NS',
  },
  {
    id: 2,
    state: 'INPLAY_1ST_HALF',
    name: '1st Half',
    short_name: '1st',
    developer_name: 'INPLAY_1ST_HALF',
  },
  {
    id: 3,
    state: 'HT',
    name: 'Half Time',
    short_name: 'HT',
    developer_name: 'HT',
  },
  {
    id: 4,
    state: 'BREAK',
    name: 'Break',
    short_name: 'BRK',
    developer_name: 'BREAK',
  },
  {
    id: 5,
    state: 'FT',
    name: 'Full Time',
    short_name: 'FT',
    developer_name: 'FT',
  },
  {
    id: 6,
    state: 'INPLAY_ET',
    name: 'Extra Time',
    short_name: 'et',
    developer_name: 'INPLAY_ET',
  },
  {
    id: 7,
    state: 'AET',
    name: 'After Extra Time',
    short_name: 'AET',
    developer_name: 'AET',
  },
  {
    id: 8,
    state: 'FT_PEN',
    name: 'After Penalties',
    short_name: 'FTP',
    developer_name: 'FT_PEN',
  },
  {
    id: 9,
    state: 'INPLAY_PENALTIES',
    name: 'Penalties',
    short_name: 'PEN',
    developer_name: 'INPLAY_PENALTIES',
  },
  {
    id: 10,
    state: 'POSTPONED',
    name: 'Postponed',
    short_name: 'POST',
    developer_name: 'POSTPONED',
  },
  {
    id: 11,
    state: 'SUSPENDED',
    name: 'Suspended',
    short_name: 'SUSP',
    developer_name: 'SUSPENDED',
  },
  {
    id: 12,
    state: 'CANCELLED',
    name: 'Cancelled',
    short_name: 'CANC',
    developer_name: 'CANCELLED',
  },
  {
    id: 13,
    state: 'TBA',
    name: 'To Be Announced',
    short_name: 'TBA',
    developer_name: 'TBA',
  },
  {
    id: 14,
    state: 'WO',
    name: 'Walk Over',
    short_name: 'WO',
    developer_name: 'WO',
  },
  {
    id: 15,
    state: 'ABANDONED',
    name: 'Abandoned',
    short_name: 'ABAN',
    developer_name: 'ABANDONED',
  },
  {
    id: 16,
    state: 'DELAYED',
    name: 'Delayed',
    short_name: 'DELA',
    developer_name: 'DELAYED',
  },
  {
    id: 17,
    state: 'AWARDED',
    name: 'Awarded',
    short_name: 'AWAR',
    developer_name: 'AWARDED',
  },
  {
    id: 18,
    state: 'INTERRUPTED',
    name: 'Interrupted',
    short_name: 'INT',
    developer_name: 'INTERRUPTED',
  },
  {
    id: 19,
    state: 'AWAITING_UPDATES',
    name: 'Awaiting Updates',
    short_name: 'AU',
    developer_name: 'AWAITING_UPDATES',
  },
  {
    id: 20,
    state: 'DELETED',
    name: 'Deleted',
    short_name: 'DEL',
    developer_name: 'DELETED',
  },
  {
    id: 21,
    state: 'EXTRA_TIME_BREAK',
    name: 'Extra Time - Break',
    short_name: 'ETB',
    developer_name: 'EXTRA_TIME_BREAK',
  },
  {
    id: 22,
    state: 'INPLAY_2ND_HALF',
    name: '2nd Half',
    short_name: '2nd',
    developer_name: 'INPLAY_2ND_HALF',
  },
  {
    id: 23,
    state: 'INPLAY_ET_2ND_HALF',
    name: 'ET - 2nd Half',
    short_name: '2et',
    developer_name: 'INPLAY_ET_2ND_HALF',
  },
  {
    id: 25,
    state: 'PEN_BREAK',
    name: 'Penalties - Break',
    short_name: 'PENB',
    developer_name: 'PEN_BREAK',
  },
  {
    id: 26,
    state: 'PENDING',
    name: 'Pending',
    short_name: 'PEN',
    developer_name: 'PENDING',
  },
];
